# This is a basic workflow that is manually triggered

name: Test utilix

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # prints something after importing utilix
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install python dependencies
      uses: py-actions/py-dependency-install@v2
    - name: Write config
      run: | 
           bash .github/scripts/create-config.sh
           python setup.py develop --user
      env:
        RUNDB_API_URL: ${{ secrets.RUNDB_API_URL }}
        RUNDB_API_USER: ${{ secrets.RUNDB_API_USER }}
        RUNDB_API_PASSWORD: ${{ secrets.RUNDB_API_PASSWORD }}
    - name: Test utilix db
      shell: python
      run: |
           import utilix
           from utilix import db
           from pprint import pprint
           data = db.get_context('xenonnt_online', '0.11.0')
           pprint(data)
            
